### ISSUE TITLE
Silenced guns are not actually silenced

### ISSUE THREAD

**Issue by MeCrafX** [HaloOfBlocks/AdditionalGuns#29]
Hello I recently found other issue

Guns like 9A-91, Vintorez and Val should be silenced but are not
![image](https://user-images.githubusercontent.com/93524313/160233099-32a11ec0-b491-4723-a56b-408d19a38f33.png)

this mean other player will still hear you and hostle mob will also hear you sooner

**Comment by MeCrafX** [comment]
oh btw I play latest version mod 1.16.5 forge

**Comment by Autovw** [comment]
This issue will remain on the to-do list for a future update since we haven't found a solution *yet*

**Comment by CasualNoLifer** [comment]
This issue will have somewhat of a fix in 0.8.0. Val, Vintorez and 9A-91 (the three integrally suppressed guns) will have their suppressors become a barrel (muzzle) attachment and not be "silenced" by default.
