### ISSUE TITLE
Some guns don't render with the correct size on the back while on offhand.

### ISSUE THREAD

**Issue by GaudiesHades** [HaloOfBlocks/AdditionalGuns#89]
There are guns, like the AWM, AUG, M4A1-S, and some more that appear smaller on the back while they are on the offhand slot. This is an example:  

AUG dropped in the ground: 

![2022-11-15_15 09 58](https://user-images.githubusercontent.com/118282708/201940629-1b3a2836-4a1a-4034-898f-2912c771d9fc.png)

AUG while on offhand:
![2022-11-15_15 10 10](https://user-images.githubusercontent.com/118282708/201940715-a55c4eab-55fa-4a79-b141-98e14b1a4504.png)

As you can see, the size is different. It is easy to detect when this happens, especially in the AWM or the SSG-08.

**Comment by Igggosha** [comment]
No one noticed it before you because no one used the off hand anyways xd

**Comment by GaudiesHades** [comment]
I don't know, putting the gun in the back is a cool feature. But yeah you're right XD

**Comment by CasualNoLifer** [comment]
> There are guns, like the AWM, AUG, M4A1-S, and some more that appear smaller on the back while they are on the offhand slot. This is an example:
> 
> AUG dropped in the ground:
> 
> ![2022-11-15_15 09 58](https://user-images.githubusercontent.com/118282708/201940629-1b3a2836-4a1a-4034-898f-2912c771d9fc.png)
> 
> AUG while on offhand: ![2022-11-15_15 10 10](https://user-images.githubusercontent.com/118282708/201940715-a55c4eab-55fa-4a79-b141-98e14b1a4504.png)
> 
> As you can see, the size is different. It is easy to detect when this happens, especially in the AWM or the SSG-08.

@GaudiesHades 

Hi, I'm going to be attempting to fix your issue soon depending on how the next several days go.

I have not played the recent Minecraft versions but is this a vanilla feature? If not, what mod is enabling items to be put on the back? If I can figure out what the mod is I can run some testing and figure out why sizing is different than it should be.

Thanks!

**Comment by GaudiesHades** [comment]
Btw this is in 1.16,5

**Comment by Autovw** [comment]
If I remember correctly the item frame position is used for this feature. Guns that require two hands to hold render on the back of the player when placed in the off-hand and guns that require one hand to hold render on the side of the player in off-hand.

This is probably because we scaled the model down to better fit into the item frame. Should be easy to "fix".

**Comment by Autovw** [comment]
This issue should be resolved in Additional Guns 0.8.0.
Feel free to re-open if you still encounter this issue.
Thanks for reporting!
