### ISSUE TITLE
When modifying recipe in data pack causes duplicate recipe.

### ISSUE THREAD

**Issue by ShadOhh** [HaloOfBlocks/AdditionalGuns#93]
When modifying the recipe in a data pack form will result in two separate recipe. The original one and the modified one to appear in the workbench and JEI.
![1](https://user-images.githubusercontent.com/69530188/214231935-c5dc6ec5-33c8-43d5-b5c5-b6aa62cb4131.png)
![2](https://user-images.githubusercontent.com/69530188/214231938-7acf85d1-98e1-427f-b691-5c4aa837edf6.png)

**Comment by Autovw** [comment]
The recipes are supposed to be placed under the ``additionalguns`` namespace and not ``cgm``. Because of this the game thinks they are new recipes, and does not override the recipes of the mod.
